### ISSUE TITLE
Did i already sign this ? Let the user know if they need to acknowledge / active this vault

### ISSUE THREAD

**Issue by darosior** [revault/revaultd#105]
> darosior
20:07
Hmm we should have a "i already signed" state don't you think? Weird to still have to acknowledge funds on homepage after succesful signing

> edouard
09:43
> yes, I can check for each vault not spent if the presigned transactions are signed  but If there are 6371 vaults it would take time to load
> maybe once revocationtxs is done, we update a column in vault table with: revocation_txs_signed: true
and the column has a field is in the resource of the listvaults call

> darosior
09:45
That's basically equivalent to having a new state

> edouard
09:46
yes, do we both agree that a new vault status is too much ?
two other column in the table could do the job:
revocation_txs_signed unvault_tx_signed

> darosior
09:55
Well i feel like the opposite (as usual lol), adding more columns seems overkiller than a new state. But the number of state is bloated. I'm thinking of a way to do it without DB
Let's put an issue for now

**Comment by edouardparis** [comment]
I think for the UI it would be really easier to have a new field in listvaults response, because the UI needs to display lists of vaults to sign, currently signed and waiting other stakeholders signatures.

This new field could be a number of transactions signed (but column integer in DB) with this values:
- 0
- 3 (revocations_tx_signed)
- 4 (unvault_signed)
- 5 (spent signed)

**Comment by darosior** [comment]
I think we have too many vault statuses but i conceptually don't get how an additional boolean makes more sense than a new status.
```
unconfirmed => funded => acknowledged => presigned => unvaulted => spent
```

**Comment by edouardparis** [comment]
Yes it is really clear.
`unconfirmed => funded => acknowledged => presigned => unvaulted => spent`
:+1: It would be really really nice for the GUI

**Comment by darosior** [comment]
In my head, `acknowledged == i signed (ie ACKed this vault)`
