### ISSUE TITLE
Configuration and Miniscript descriptors

### ISSUE THREAD

**Issue by darosior** [revault/revaultd#108]
Right now, we take the descriptors parameters from the config (xpubs, unvault csv) in order to create a Miniscript descriptor on first startup.
This is kind of a bridge between the pre-Miniscript era where users were used to just put xpubs and It Works :tm: and the Miniscript era as if it's not first start we'll refuse to start with a config that does not correspond to the Miniscript descriptor stored in DB.

Is it the right approach ? At the end of the reflexion i believe this is a question of how modular we would like to be. It's just that we could store the Miniscript descriptor in the config directly as they are expected to be generated in advance (during the ceremony).
It would also be less regular-user friendly, redundant with the database, and we can't just change the descriptors and get everything to work immediately..

So the question(s) to answer here is:
- Do we want to keep a configuration with a list of xpubs and parameters (such as the Unvault CSV value), or should we move to store the Miniscript descriptors right in the config ?

**Comment by darosior** [comment]
Related: https://github.com/revault/revault_tx/issues/64

**Comment by kloaec** [comment]
That also brings the question of what happens if a client changes the config (no matter which choice we go for) in a production environment.
IMHO this config should only be used at ceremony to generate the descriptor, and set once and for all.
It seems to me that a config file would imply that these can be changed: they should not.

**Comment by darosior** [comment]
Agreed. Right now if the config is changed and a database exists with descriptors we would abort the startup (at least we should, i think we would silently go with the DB one right now but it's not the expected behaviour).

**Comment by kloaec** [comment]
Then let's say this initialisation is done at ceremony, and that's it. We can record the parameters during the ceremony for backup purpose as well maybe.
Something like: if first start, then look for Init.conf , import (and rename or delete). If not first start, either no check for init.conf, or error prompt "this wallet is already initialized, why the fuck do you have an init.conf in there?"

**Comment by darosior** [comment]
Adding to the bottom of the queue of the March demo deadline. We can go without but it's better to have a proper config to test the setup / ceremony while we are together.

**Comment by darosior** [comment]
Removing from the milestone, but will take care of it asap
