### ISSUE TITLE
filter `listspendtxs` result

### ISSUE THREAD

**Issue by darosior** [revault/revaultd#121]
[`listspendtxs` is upcoming]
We could filter by vault outpoints, or spend txids.. To be discussed here first to implementing it :)

**Comment by edouardparis** [comment]
Maybe by destination address

**Comment by darosior** [comment]
If you want to have a filter by destination, i think it should be by label and not by address

**Comment by darosior** [comment]
Related: https://github.com/revault/revault-gui/issues/87 . We could have a filter by "non final", "final", "broadcasted" (or better terms..). @danielabrozzoni can you take care of this?

**Comment by danielabrozzoni** [comment]
On it :)

**Comment by danielabrozzoni** [comment]
I think we should also distinguish between broadcasted, confirmed and canceled?
From the UI perspective you want to show broadcasted ones as "pending", but not the confirmed and canceled

**Comment by darosior** [comment]
Yes, i think we should for the RPC interface
