### ISSUE TITLE
An RPC command for broadcasting Emergency for a vault

### ISSUE THREAD

**Issue by darosior** [revault/revaultd#127]
We may want to do it for all the vaults at once: i can't think of a scenario where one would want to only emergency a single vault.

For a single vault it could be `emergencyburry <deposit_outpoint>`.

For all the vaults it could just be `emergency`, `takedown` (?) without any parameter.

@kloaec , @edouardparis thoughts ?

**Comment by edouardparis** [comment]
Concept ACK

**Comment by darosior** [comment]
> Concept ACK

It was to discuss the two possibilities and choose one of them, actually :sweat_smile:

**Comment by edouardparis** [comment]
or maybe:
`emergency [outpoints, ...]` and `emergency all`

**Comment by darosior** [comment]
Actually i think that we don't need to be flexible on this one. We should just have an `emergency` RPC command that broadcast all Emergency transaction, basta. Why would you broadcast a single one anyways?
