### ISSUE TITLE
Add a `help` command

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revaultd#141]
Add a `help` command which prints all the available commands, so I don't have to open `doc/API.md` every time :D

**Comment by darosior** [comment]
I think that'd be a good thing to have, could you give more specific instructions for someone to be able to start working on it? Like the expected JSON output.

**Comment by danielabrozzoni** [comment]
I would say something like this:

```
{
  "commands":[
    {
      "name":"getinfo",
      "parameters":[
        
      ],
      "description":"Display general information"
    },
    {
      "name":"getrevocationtxs",
      "parameters":[
        "outpoint"
      ],
      "description":"Retrieve the Revault revocation transactions to sign"
    }
  ]
}
```

- The description should be the same as in `doc/API.md`
- Optional parameters should be enclosed in `[` `]`, for example:
```
"parameters":[
  "[outpoint]",
  "[status]",
],
```
means that both `outpoint` and `status` are optional
