### ISSUE TITLE
psbtsigner should return a json

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revaultd#222]
Either we make it default or at least we add an option to return a json object, this way it's easier to use in scripts :)

**Comment by darosior** [comment]
Yes, on a more general note i'm a bit worried with augmenting and patching psbtsigner. It was initially, and still is in some way, a hack that i used locally for my manual testing and just ended up committing there for reviewers to use too. If we need something we should probably opt for something more generalistic. Especially in scripts, one could extend the Python support in the test framework and separate it in a script.

**Comment by darosior** [comment]
For the manual testing part, maybe contributing signing support to https://github.com/stevenroose/hal would be preferable?

**Comment by darosior** [comment]
So Sanket implemented that in Hal! https://github.com/stevenroose/hal/pull/25 :tada:

**Comment by danielabrozzoni** [comment]
Should we remove the psbtsigner altogether?

**Comment by darosior** [comment]
Yeah, it was meant as a temporary hack. I haven't used it in months, and looks like Hal can do basically the same (and if it doesn't we can just contribute a small tweak there). I'm for removing it.

@edouardparis do you have any use for psbtsigner or we can remove it?

**Comment by edouardparis** [comment]
No use for me :+1:

**Comment by darosior** [comment]
Closing in favour of https://github.com/revault/revaultd/issues/358
