### ISSUE TITLE
Specify multiple inputs to be signed to psbtsigner

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revaultd#223]
This is to be discussed, but it would be cool to sign multiple inputs of the psbt in just one command. Maybe we should sign every input, unless otherwise specified? Maybe we should be able to specify a range?

(I tried to sign a 15-inputs PSBT and I got so bored that I avoided the spend altogether...)

**Comment by darosior** [comment]
Closing in favour of https://github.com/revault/revaultd/issues/358
