### ISSUE TITLE
revaultd lib: expose daemon and revaultd module + libsodium dep

### ISSUE THREAD

**Issue by edouardparis** [revault/revaultd#270]
for import in the gui, it needs:
- `revaultd::Revaultd`
- `main::daemon_main` -> to move to `daemon` ?
- `sodiumoxide`  maybe expose the dep in lib.rs ?

**Comment by darosior** [comment]
`RevaultD` can be made `pub`
Same for `daemon_main`. Sure for the move, maybe we can epurate it more and make it `RevaultD::main`?
`sodiumoxide` is already re-exported by `revault_net` so you can use that? Or is it not The Right Way?
