### ISSUE TITLE
I broke revaultd, I don't know how

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revaultd#273]
Or maybe I broke the coordinator, who knows.

I was quite in a rush and trying to delegate a vault in a 1 manstake and 1 stake environment, and I don't know how, I managed to break revaultd :sob:
Manager-stakeholder now has a vault "securing":
```
{
        "address": "bcrt1qvaekeavuxqjzedwkv7ccdh7muv644m9822tu4f8x0nl3pqh5fgasgytah8",
        "amount": 4999946888,
        "blockheight": 152,
        "derivation_index": 0,
        "received_at": 1631106370,
        "status": "securing",
        "txid": "b91dcaec8cae26c485072eaf7c2f03ee7ac941211854064b25dfd4bf6a12aca8",
        "updated_at": 1631609294,
        "vout": 0
      }
```
The other stakeholder (we'll call it `stake2`) has it as "activating":
```
      {
        "address": "bcrt1qvaekeavuxqjzedwkv7ccdh7muv644m9822tu4f8x0nl3pqh5fgasgytah8",
        "amount": 4999946888,
        "blockheight": 152,
        "derivation_index": 0,
        "received_at": 1631106370,
        "status": "activating",
        "txid": "b91dcaec8cae26c485072eaf7c2f03ee7ac941211854064b25dfd4bf6a12aca8",
        "updated_at": 1632420264,
        "vout": 0
      },
```
I don't know which steps I took, but my guess is:
1. Secure with stakeman
2. Shut down coordinator
3. Start the stake2 revaultd, which will show the vault as "funded"
4. Secure and delegate with stake2
5. Tada

**Comment by darosior** [comment]
Why is it broken? I think the following scenario could lead to the same state and that it's supported:
- Stake1 shares their revoc signatures (`securing`)
- Stake2 polls these signatures, shares their revoc signatures (`securing`)
- Before Stake1 even polls the coordinator, stake2 pushes their unvault signatures (`activating`) (and Stake1 still `securing`)

**Comment by danielabrozzoni** [comment]
That's supported for a brief amount of time, but then revaultd should sync with the coordinator and they both should reach the activating state.

Now that I think about it, I might have deleted the coordinator database 😅  That might be it. I'll re-upload the transactions to the database and see if they sync.

**Comment by danielabrozzoni** [comment]
Actually, maybe we should add a `coordinatord_sync` RPC call, where we send everything we have to the coordinatord? You know, in case you're a smart person like me and you delete the database. :)

**Comment by danielabrozzoni** [comment]
Closing this in favor of #319
