### ISSUE TITLE
Check bitcoind version at startup

### ISSUE THREAD

**Issue by darosior** [revault/revaultd#324]
`bitcoind`'s releases are versioned. New releases bring new features. `revaultd` depends on the newest features of `bitcoind`. Checking the version at startup is for sanity checking that the features we depend on are available on the `bitcoind` we are configured to talk to.

**Comment by gourab337** [comment]
@darosior I added a pr some days back: https://github.com/revault/revaultd/pull/378

**Comment by darosior** [comment]
@gourab337 please note that a PR needs to pass CI before being considered. Also, your PR does not seem to fix this issue in its current form.
