### ISSUE TITLE
Add participant kind in `getinfo`

### ISSUE THREAD

**Issue by darosior** [revault/revaultd#45]
I think @edouardparis will need to know if the `revaultd` is configured for a stakeholder or a manager without actually parsing the config ?

**Comment by edouardparis** [comment]
revault-gui need to parse the config to get the datadir and find the socket path, It can parse the `user role` in the config

**Comment by darosior** [comment]
Hmm right, but i still think we should do it for applications that don't want to be parsing the config

**Comment by edouardparis** [comment]
ACK :+1:

**Comment by darosior** [comment]
Similarly to #174 this is about adding a new field in `getinfo`.

The key could be `participant_type` and the value should be the "kind" of participants, `stakeholder`, `stakeholdermanager`, or `manager`.
Useful skills for solving this issues:
- Knowing what these kinds correspond to
- Knowledge about the config parsing, to see where (and on what basis) we set whether a participant is a stk, stkman or man
- Being familiar with the `RevaultD` "main state data structure" to be able to forward this information to the JSONRPC interface

**Comment by darosior** [comment]
Done in #387
